create database mydatabase;
use mydatabase;
select * from mytable;

#--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from mytable
group by gender;
 
#--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from mytable
where discount_applied = 'YES' and purchase_amount >= (select avg(purchase_amount) from mytable);

#-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) as highest_rating
from mytable
group by item_purchased
order by avg(review_rating) desc limit 5;

#--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2)
from mytable
where shipping_type in ('Express','Standard')
group by shipping_type;

#--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, avg(purchase_amount) as avg_spend,sum(purchase_amount)as total_revenue
from mytable
group by subscription_status;

#--Q6. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

select 
   case 
      when previous_purchases = 1 then 'New'
	  when previous_purchases between 2 and 10 then 'Returning'
      else 'Loyal'
   end
     as customer_segment,
	 count(*) as customer_count
from mytable
group by customer_segment;

#--Q7. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5 and subscription_status = 'Yes'
group by subscription_status;

#--Q9. What is the revenue contribution of each age group? 

select age_groups,sum(purchase_amount) as revenue
from mytable
group by age_groups
order by revenue desc